// Singleton client for the LMS database (separate Neon project).
// Mirrors lib/prisma.ts but imports the isolated client generated by
// prisma/lms/schema.prisma and uses its own global key so the two
// Prisma clients never alias each other.
//
// Run `npm run lms:generate` to (re)generate the client this imports.
import { PrismaClient } from '.prisma/lms-client';

const globalForLms = globalThis as unknown as { lmsPrisma?: PrismaClient };

export const lmsPrisma = globalForLms.lmsPrisma ?? new PrismaClient();

if (process.env.NODE_ENV !== 'production') {
  globalForLms.lmsPrisma = lmsPrisma;
}
